package com.client.application.enduser.selenium;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.HashMap;
import java.util.Map;

import static org.hamcrest.CoreMatchers.is;
import static org.junit.Assert.assertThat;


public class SearchBookTitleTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<>();
    driver.get("http://localhost:8081/");
    driver.manage().window().setSize(new Dimension(1848, 1053));
  }
  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void searchBookTitle() throws InterruptedException {

    driver.findElement(By.id("findBook")).click();
    driver.findElement(By.id("findBook")).sendKeys("Book1");
    driver.findElement(By.id("book_title")).click();
    driver.findElement(By.id("search_book")).click();
    WebDriverWait wait = new WebDriverWait(driver, 30);
    WebElement selectPollutant = wait.until(ExpectedConditions.elementToBeClickable(By.id("book_title 1")));
    selectPollutant.click();
    assertThat(driver.findElement(By.id("book_title 1")).getText(), is("Book1"));
  }
}
