package com.client.application.enduser.selenium;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class TotalcommissionsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void totalcommissions() {
    driver.get("http://localhost:8081/adminIndex.html");
    driver.manage().window().setSize(new Dimension(1294, 741));
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Your Comissions"));
    assertThat(driver.findElement(By.id("commission_amount 1")).getText(), is("Amount: 2 €"));
    assertThat(driver.findElement(By.id("commission_amount 2")).getText(), is("Amount: 2 €"));
    assertThat(driver.findElement(By.id("commission_amount 3")).getText(), is("Amount: 5 €"));
    assertThat(driver.findElement(By.id("commission_amount 4")).getText(), is("Amount: 10 €"));
    assertThat(driver.findElement(By.id("finalPrice")).getText(), is("Commission Total: 19€"));
  }
}
