package selenium;// Generated by Selenium IDE
import com.client.application.enduser.EndUserApplication;
import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.containsString;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.junit.runner.RunWith;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
@RunWith(SpringRunner.class)
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.DEFINED_PORT, classes = EndUserApplication.class)
public class PublisherTestIT {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() throws InterruptedException {
    ChromeOptions options = new ChromeOptions();
    options.addArguments("--headless", "--disable-gpu");
    driver = new ChromeDriver(options);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<>();
    driver.get("http://localhost:8080/login.html");
    logIN();

  }
  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void seeStock() {
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("seeStock")).click();
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Your Stock"));
  }
  @Test
  public void revenues() {
    driver.findElement(By.cssSelector("h1")).click();
    assertThat(driver.findElement(By.cssSelector("h1")).getText(), is("Revenue"));

  }
  @Test
  public void total() {
    WebDriverWait wait = new WebDriverWait(driver, 10);
    List<WebElement> elements = driver.findElements(By.id("finalPrice"));
    assert(elements.size() > 0);

  }
  @Test
  public void addBookError() {
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("addBook")).click();
    driver.findElement(By.id("create_ISBN")).click();
    driver.findElement(By.id("create_ISBN")).sendKeys("1111111111114");
    driver.findElement(By.id("create_Title")).click();
    driver.findElement(By.id("create_Title")).sendKeys("Book3");
    driver.findElement(By.id("BookToAdd")).click();
    try {
      WebDriverWait wait = new WebDriverWait(driver, 10);
      wait.until(ExpectedConditions.alertIsPresent());
      Alert alert = driver.switchTo().alert();
      Assert.assertTrue(alert.getText().contains("Something is Missing! Did not Create"));
      alert.accept();
    } catch (Exception e) {
      System.err.println(e);
    }
  }

 /* @Test
  public void addBookSuccess() {
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("addBook")).click();
    driver.findElement(By.id("create_ISBN")).click();
    driver.findElement(By.id("create_ISBN")).sendKeys("1111111111114");
    driver.findElement(By.id("create_Title")).click();
    driver.findElement(By.id("create_Title")).sendKeys("Book3");
    driver.findElement(By.id("create_Author")).click();
    driver.findElement(By.id("create_Author")).sendKeys("An Author");
    driver.findElement(By.id("create_Category")).click();
    driver.findElement(By.id("create_Category")).sendKeys("SciFi");
    driver.findElement(By.id("create_Description")).click();
    driver.findElement(By.id("create_Description")).sendKeys("A description");
    driver.findElement(By.id("create_Price")).click();
    driver.findElement(By.id("create_Price")).sendKeys("12.5");
    driver.findElement(By.id("create_Quantity")).click();
    driver.findElement(By.id("create_Quantity")).sendKeys("2");
    driver.findElement(By.id("BookToAdd")).click();
    try {
      WebDriverWait wait = new WebDriverWait(driver, 10);
      wait.until(ExpectedConditions.alertIsPresent());
      Alert alert = driver.switchTo().alert();
      Assert.assertTrue(alert.getText().contains("Book Created"));
      alert.accept();
    } catch (Exception e) {
      System.err.println(e);
    }
  }*/
  @Test
  public void badUpdate() {
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("updateStock")).click();
    driver.findElement(By.id("isbn")).click();
    driver.findElement(By.id("isbn")).sendKeys("1111");
    driver.findElement(By.id("quantity")).click();
    driver.findElement(By.id("quantity")).sendKeys("0");
    driver.findElement(By.id("updateBook")).click();
    try {
      WebDriverWait wait = new WebDriverWait(driver, 10);
      wait.until(ExpectedConditions.alertIsPresent());
      Alert alert = driver.switchTo().alert();
      Assert.assertTrue(alert.getText().contains("Quantity cannot not be less than 1"));
      alert.accept();
    } catch (Exception e) {
      System.err.println(e);
    }
  }
  @Test
  public void updateBookSucess() {
    driver.findElement(By.id("name")).click();
    driver.findElement(By.id("updateStock")).click();
    driver.findElement(By.id("isbn")).click();
    driver.findElement(By.id("isbn")).sendKeys("1111111111111");
    driver.findElement(By.id("quantity")).click();
    driver.findElement(By.id("quantity")).sendKeys("2");
    driver.findElement(By.id("updateBook")).click();
    try {
      WebDriverWait wait = new WebDriverWait(driver, 10);
      wait.until(ExpectedConditions.alertIsPresent());
      Alert alert = driver.switchTo().alert();
      Assert.assertTrue(alert.getText().contains("Updated"));
      alert.accept();
    } catch (Exception e) {
      System.err.println(e);
    }
  }

  public void logIN () throws InterruptedException {
    driver.findElement(By.id("inputUsername")).click();
    driver.findElement(By.id("inputUsername")).sendKeys("pub1");
    driver.findElement(By.id("inputPassword")).sendKeys("pw");
    driver.findElement(By.id("signIn")).click();
    try {
      WebDriverWait wait = new WebDriverWait(driver, 5);
      wait.until(ExpectedConditions.alertIsPresent());
      Alert alert = driver.switchTo().alert();
      alert.accept();
    } catch (Exception e) {
      System.err.println(e);
    }
    Thread.sleep(1000);
    driver.findElement(By.id("signIn")).click();
  }
}
